### ISSUE TITLE
Removing include_home config

### ISSUE THREAD

**Issue by federicovilla** [avenirer/CI-breadcrumb-library#1]
Hi Adrian,
first of all thanks for the great script.
I just got in trouble with config file: if I leave the $config['include_home'] configuration variable empty I should get rid of Home in the breadcrumbs...but I get it the same with the link of the home page.

Now just a couple of request:
- can I add an icon just to the Home breadcrumb? For example the following code before the text Home
`<i class="fa fa-home pr-10">`
so, the first breadcrumb should be:
`<li><i class="fa fa-home pr-10"></i><a href="index.html">Home</a></li>`

- second question: is there a way to set breadcrumb library multilanguage?

Thanks a lot

**Comment by avenirer** [comment]
It shouldn't do that...

If you want it the way you said, you could try

``` php
$config['include_home'] = '<i class="fa fa-home pr-10"></i> Home';
```

Why? Because the home icon is also a part of the link (at least regarding from an usability point of view...).

Regarding the multilanguage... what do you mean? The breadcrumb only uses what you give it. :)

**Comment by federicovilla** [comment]
Hi Adrian, thanks a lot for quick feedback.

About the first reply...this is exactly what I did in config file...but I got a weird result in web page: http://gavs.it/_gavs2/about

About multilanguage I got it...thanks.

**Comment by federicovilla** [comment]
This is what I get adding the i class:
`<ol class="breadcrumb">
       <li><a href="http://gavs.it/_gavs2"><i class="fa fa-home pr-10"> Home</a></li>
       <li class="active">About</li>
</ol>`

This is what I'd like to get:
`<ol class="breadcrumb">
    <li><i class="fa fa-home pr-10"></i><a href="http://gavs.it/_gavs2/home">Home</a></li>
    <li class="active">About Us</li>
</ol>`

So I'd like to get the <i class="fa fa-home pr-10"> outside the a href anchor

**Comment by avenirer** [comment]
I understand what you like to get, but it is not possible.

**Comment by federicovilla** [comment]
Thanks for feedback Adrian.
I did it...don't know if my new code is the best solution...but it works.
I have a new config item: icon
The library check if the config entry exixts and append it to the $output string before the anchor.
